const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

/**
 * Draws the official DJMHS Letterhead Header onto a PDF document.
 * This ensures strict brand consistency across all PDFs generated by the ERP.
 * @param {PDFKit.PDFDocument} doc 
 */
const drawLetterhead = (doc) => {
  // We can fetch dynamic branding from DB here if passed, but for now we use the official hardcoded tokens
  const primaryColor = '#123E97';
  const secondaryColor = '#0B2D78';
  const goldenAccent = '#F2B233';

  // 1. Trust Name Banner (Top)
  doc.rect(0, 0, doc.page.width, 30).fill(secondaryColor);
  doc.fontSize(10).fillColor('#FFFFFF')
     .text('Bhavnagar Kelavani Mandal, Bhavnagar Sanchalit', 0, 10, { align: 'center', width: doc.page.width });

  // 2. Main School Header Background (Optional light tint or just white)
  doc.rect(0, 30, doc.page.width, 100).fill('#FFFFFF');

  // 3. Logo Placeholder (Left)
  // In a real env, load from path.join(__dirname, '../../uploads/logo.png')
  const logoPath = path.join(__dirname, '../../uploads/logo_dummy.png');
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, 40, 45, { width: 60 });
  } else {
    // Draw dummy circle if logo missing
    doc.circle(70, 75, 30).fillAndStroke('#F8FAFC', primaryColor);
    doc.fillColor(primaryColor).fontSize(8).text('LOGO', 55, 72);
  }

  // 4. Main School Title
  doc.fontSize(18).font('Helvetica-Bold').fillColor(primaryColor)
     .text('SHREE DHANESHKUMAR JASVANTLAL MAHETA HIGH SCHOOL', 120, 50, { width: 400, align: 'center' });
  
  // Address & Index No
  doc.fontSize(10).font('Helvetica').fillColor('#334155')
     .text('Gandhismruti Pase, Bhavnagar - 364 001. Ph.: 0278-2423896', 120, 90, { width: 400, align: 'center' });
  doc.fontSize(9).fillColor(secondaryColor)
     .text('School Index No. :- S.S.C. 62.0009  H.S.C. :- 12.0026', 120, 105, { width: 400, align: 'center' });

  // 5. Bottom Banner (Ribbon)
  doc.rect(0, 130, doc.page.width, 5).fill(goldenAccent);
  
  // Reset Y coordinate for content body
  doc.y = 160;
  doc.x = 50;
};

/**
 * Generate a formal PDF Fee Payment Receipt in memory and return as Buffer
 */
const generateFeeReceiptPDF = async (payment) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Draw standard letterhead
      drawLetterhead(doc);

      doc.fontSize(14).fillColor('#334155').text('OFFICIAL FEE RECEIPT', { align: 'center', underline: true }).moveDown(1.5);

      // Receipt Details & Metainfo
      const student = payment.student || {};
      const division = student.division || {};
      const installment = payment.feeInstallment || {};

      doc.fontSize(11).fillColor('#1e293b');
      doc.text(`Receipt No: ${payment.receiptNo}`, 50, 200);
      doc.text(`Date: ${new Date(payment.paymentDate).toLocaleDateString()}`, 350, 200);

      doc.text(`Student Name: ${student.firstName} ${student.lastName}`, 50, 225);
      doc.text(`GR Number: ${student.grNumber || 'N/A'}`, 350, 225);

      doc.text(`Standard & Division: ${division.name || 'Standard Assigned'}`, 50, 250);
      doc.text(`Roll No: ${student.rollNumber || 'N/A'}`, 350, 250);

      doc.moveDown(2);
      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, 280).lineTo(545, 280).stroke();

      // Table Headers
      doc.fontSize(11).fillColor('#123E97');
      doc.text('Fee Head & Installment Description', 60, 295);
      doc.text('Payment Method', 350, 295);
      doc.text('Amount (INR)', 450, 295);

      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, 315).lineTo(545, 315).stroke();

      // Row content
      doc.fontSize(11).fillColor('#1e293b');
      doc.text(installment.title || 'Tuition / Academic Fee Installment', 60, 330);
      doc.text(payment.paymentMethod + (payment.transactionId ? ` (${payment.transactionId})` : ''), 350, 330);
      doc.text(`INR ${payment.amount.toFixed(2)}`, 450, 330);

      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, 360).lineTo(545, 360).stroke();

      // Total & Authorization Summary
      doc.fontSize(12).fillColor('#123E97').font('Helvetica-Bold');
      doc.text(`Total Paid Amount: INR ${payment.amount.toFixed(2)}`, 320, 380, { align: 'right', width: 225 });

      doc.moveDown(5);
      doc.fontSize(10).fillColor('#64748b').font('Helvetica');
      doc.text('Note: This is an electronically generated official receipt verified by DJMHS ERP. No physical signature required.', 50, 480, { align: 'center', width: 495 });
      doc.text('Authorized Cashier / Accounts Office - DJMHS', 300, 530, { align: 'right', width: 245 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate PDF Report Card for Student Academic Results
 */
const generateReportCardPDF = async (result, student, exam, marksList) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Draw standard letterhead
      drawLetterhead(doc);

      doc.fontSize(14).fillColor('#334155').text(`ACADEMIC PERFORMANCE REPORT — ${exam.name}`, { align: 'center' }).moveDown(1.5);

      doc.fontSize(11).fillColor('#1e293b');
      doc.text(`Student: ${student.firstName} ${student.lastName}`, 50, 200);
      doc.text(`GR Number: ${student.grNumber}`, 350, 200);
      doc.text(`Roll Number: ${student.rollNumber}`, 50, 225);
      doc.text(`Result Status: ${result.status}`, 350, 225, { underline: true });

      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, 255).lineTo(545, 255).stroke();

      doc.fontSize(11).fillColor('#123E97').font('Helvetica-Bold');
      doc.text('Subject', 60, 265);
      doc.text('Max Marks', 250, 265);
      doc.text('Obtained Marks', 350, 265);
      doc.text('Grade', 480, 265);

      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, 285).lineTo(545, 285).stroke();

      let yPos = 300;
      doc.font('Helvetica');
      marksList.forEach((m) => {
        const subjName = m.examSchedule?.subject?.name || 'Subject';
        const max = m.examSchedule?.maxMarks || 100;
        const obt = m.isAbsent ? 'ABSENT' : (m.marksObtained ?? 'N/A');

        doc.fontSize(10).fillColor('#1e293b');
        doc.text(subjName, 60, yPos);
        doc.text(`${max}`, 250, yPos);
        doc.text(`${obt}`, 350, yPos);
        doc.text(m.grade || '-', 480, yPos);
        yPos += 25;
      });

      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, yPos).lineTo(545, yPos).stroke();
      yPos += 15;

      doc.fontSize(12).fillColor('#123E97').font('Helvetica-Bold');
      doc.text(`Total Score: ${result.totalMarks} | Percentage: ${result.percentage.toFixed(2)}% | Overall Grade: ${result.grade}`, 50, yPos, { align: 'center', width: 495 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = {
  drawLetterhead,
  generateFeeReceiptPDF,
  generateReportCardPDF,
};
