import React, { useState, useEffect } from 'react';
import { Clock, Calendar, Plus, ShieldAlert, CheckCircle2, User, BookOpen } from 'lucide-react';
import api from '../../services/api';
import TimetableService from '../../services/timetable.service';
import TimetableCellModal from './TimetableCellModal';
import Modal from '../../components/Modal/Modal';
import LoadingSkeleton from '../../components/States/LoadingSkeleton';
import { useTranslation } from 'react-i18next';

const days = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'];
const periods = [
  { p: 1, time: '07:30 AM — 08:20 AM', label: 'Period 1' },
  { p: 2, time: '08:20 AM — 09:10 AM', label: 'Period 2' },
  { p: 3, time: '09:10 AM — 10:00 AM', label: 'Period 3' },
  { p: 'break', time: '10:00 AM — 10:30 AM', label: 'Morning Recess / Nutrition Break' },
  { p: 4, time: '10:30 AM — 11:20 AM', label: 'Period 4' },
  { p: 5, time: '11:20 AM — 12:10 PM', label: 'Period 5' },
  { p: 6, time: '12:10 PM — 01:00 PM', label: 'Period 6' },
];

const TimetablePage: React.FC = () => {
  const { t } = useTranslation();
  const [divisions, setDivisions] = useState<any[]>([]);
  const [selectedDivision, setSelectedDivision] = useState<string>('');
  const [scheduleData, setScheduleData] = useState<Record<string, any>>({});
  const [loading, setLoading] = useState<boolean>(true);
  const [activeCell, setActiveCell] = useState<{ day: string; period: string; time: string; existing?: any } | null>(null);
  const [toastMsg, setToastMsg] = useState<string | null>(null);
  const [generatingDraft, setGeneratingDraft] = useState(false);
  const [draftData, setDraftData] = useState<any | null>(null);

  const handleAutoGenerateDraft = async () => {
    setGeneratingDraft(true);
    try {
      const res = await api.post('/timetables/generate-draft', { periodsPerDay: 6 });
      setDraftData(res.data.data);
    } catch (e: any) {
      setToastMsg(e.response?.data?.message || 'Failed to auto-generate timetable draft.');
      setTimeout(() => setToastMsg(null), 4000);
    } finally {
      setGeneratingDraft(false);
    }
  };

  const handleApproveDraft = async () => {
    if (!draftData) return;
    setLoading(true);
    try {
      const res = await api.post('/timetables/approve-draft', { draftId: draftData.draftId });
      setToastMsg(`Timetable draft approved! ${res.data.data.committedCount} period assignments committed to database.`);
      setDraftData(null);
      fetchSchedule();
    } catch (e: any) {
      setToastMsg(e.response?.data?.message || 'Failed to approve draft.');
    } finally {
      setLoading(false);
      setTimeout(() => setToastMsg(null), 5000);
    }
  };

  const fetchSchedule = async () => {
    if (!selectedDivision) return;
    setLoading(true);
    try {
      const slots = await TimetableService.getTimetable(selectedDivision);
      const map: Record<string, any> = {};
      if (Array.isArray(slots)) {
        slots.forEach((s: any) => {
          map[`${s.dayOfWeek}_${s.periodNumber}`] = s;
        });
      }
      setScheduleData(map);
    } catch (e) {
      setScheduleData({});
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const fetchMetadata = async () => {
      try {
        const res = await api.get('/settings');
        const list: any[] = [];
        res.data.data.standards.forEach((std: any) => {
          std.divisions.forEach((div: any) => {
            list.push({
              id: div.id,
              name: `${std.name} — Division ${div.name} (Room ${div.roomNumber || 'N/A'})`,
            });
          });
        });
        setDivisions(list);
        if (list.length > 0) setSelectedDivision(list[0].id);
      } catch (err) {
        setDivisions([]);
        setSelectedDivision('');
      }
    };
    fetchMetadata();
  }, []);

  useEffect(() => {
    fetchSchedule();
  }, [selectedDivision]);

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      
      {toastMsg && (
        <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold flex items-center gap-2 shadow-xs">
          <CheckCircle2 className="w-5 h-5 text-emerald-600" /> {toastMsg}
        </div>
      )}

      {/* Control Banner */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-soft flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <span className="text-[10px] font-extrabold uppercase bg-primary-50 text-primary-700 px-2.5 py-0.5 rounded border border-primary-200">
            <Clock className="w-3.5 h-3.5 inline mr-1" /> {t('timetable_console_tag')}
          </span>
          <h2 className="text-2xl font-black text-slate-900 mt-1">{t('timetable_matrix_title')}</h2>
          <p className="text-xs text-slate-500">{t('timetable_matrix_subtitle')}</p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <button
            disabled={generatingDraft}
            onClick={handleAutoGenerateDraft}
            className="px-4 py-2.5 rounded-xl border border-primary-300 bg-primary-50 hover:bg-primary-100 text-primary-900 font-extrabold text-xs transition flex items-center gap-2 shadow-xs"
          >
            <Clock className="w-4 h-4 text-primary-700" />
            {generatingDraft ? 'Generating Draft...' : 'Auto-Generate Timetable Draft'}
          </button>

          <div>
            <label className="block text-[10px] font-bold uppercase text-slate-400 mb-1">{t('target_schedule')}</label>
            <select
              value={selectedDivision}
              onChange={(e) => setSelectedDivision(e.target.value)}
              className="p-3 border border-slate-300 rounded-xl text-xs font-black bg-white cursor-pointer w-full sm:w-64"
            >
              {divisions.map((div) => (
                <option key={div.id} value={div.id}>
                  {div.name}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Matrix Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-soft overflow-hidden">
        <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between text-xs font-extrabold text-slate-700">
          <span>{t('weekly_academic_routine')}</span>
          <span>{t('click_cell_to_assign')}</span>
        </div>

        {loading ? <LoadingSkeleton rows={7} /> : (
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-xs">
              <thead>
                <tr className="bg-slate-800 text-white uppercase text-center font-extrabold border-b border-slate-700">
                  <th className="py-4 px-4 w-48 text-left bg-slate-900">{t('day_time_slot')}</th>
                  {periods.map((p, idx) => (
                    <th key={idx} className={`py-4 px-3 w-36 ${p.p === 'break' ? 'bg-amber-400 text-slate-900 w-24 font-black' : ''}`}>
                      <div className="text-[11px] uppercase tracking-wide">{p.label}</div>
                      <div className="text-[10px] font-normal opacity-80">{p.time.split(' — ')[0]}</div>
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 font-medium">
                {days.map((day) => (
                  <tr key={day} className="hover:bg-slate-50/50 transition">
                    <td className="py-5 px-4 font-black text-slate-900 bg-slate-50/80 border-r border-slate-200 uppercase tracking-tight text-sm">
                      {day}
                    </td>
                    {periods.map((p, pIdx) => {
                      if (p.p === 'break') {
                        return (
                          <td key={pIdx} className="bg-amber-50/60 text-center text-amber-900 font-extrabold text-[10px] border-r border-slate-200 uppercase tracking-wide px-1 select-none">
                            {t('recess')}
                          </td>
                        );
                      }

                      const timeKey = p.time.split(' — ')[0];
                      const slot = scheduleData[`${day}_${timeKey}`];

                      return (
                        <td
                          key={pIdx}
                          onClick={() => setActiveCell({ day, period: p.label, time: p.time, existing: slot })}
                          className="p-3 border-r border-slate-100 hover:bg-primary-50/40 cursor-pointer transition relative min-h-[90px] h-[90px] align-top group"
                        >
                          {slot ? (
                            <div className="space-y-1">
                              <div className="font-extrabold text-primary-900 text-xs flex items-center gap-1">
                                <BookOpen className="w-3 h-3 text-primary-600 flex-shrink-0" />
                                <span className="truncate">{slot.subject.name}</span>
                              </div>
                              <div className="text-[11px] font-bold text-slate-600 flex items-center gap-1">
                                <User className="w-3 h-3 text-slate-400 flex-shrink-0" />
                                <span className="truncate">{slot.staff.firstName} {slot.staff.lastName}</span>
                              </div>
                              <div className="text-[10px] font-mono font-extrabold text-amber-800 bg-amber-100 px-1.5 py-0.5 rounded inline-block mt-1">
                                {slot.roomNumber || 'Room 101'}
                              </div>
                            </div>
                          ) : (
                            <div className="h-full w-full border border-dashed border-slate-200 rounded-xl flex items-center justify-center text-slate-400 text-[11px] font-bold group-hover:border-primary-400 group-hover:text-primary-600 transition">
                              {t('assign_slot')}
                            </div>
                          )}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {activeCell && (
        <TimetableCellModal
          isOpen={!!activeCell}
          divisionId={selectedDivision}
          dayOfWeek={activeCell.day}
          periodLabel={activeCell.period}
          timeRange={activeCell.time}
          initialData={activeCell.existing}
          onClose={() => setActiveCell(null)}
          onSuccess={(msg) => {
            fetchSchedule();
            setToastMsg(msg || 'Schedule updated and teacher clash detection verified successfully.');
            setTimeout(() => setToastMsg(null), 5000);
          }}
        />
      )}

      {draftData && (
        <Modal
          isOpen={!!draftData}
          onClose={() => setDraftData(null)}
          title="Automatic Timetable Generator — Candidate Draft Review"
          subtitle="Review candidate schedule assignments, detected clashes, and workload distribution before approving database commit."
          maxWidth="4xl"
        >
          <div className="space-y-6">
            <div className="flex items-center justify-between p-4 rounded-xl bg-slate-900 text-white">
              <div>
                <span className="px-2.5 py-0.5 rounded-full bg-amber-400 text-slate-900 font-black text-[10px] uppercase">DRAFT PREVIEW</span>
                <h4 className="font-extrabold text-base text-white mt-1">Generated {draftData.totalSlots} Period Assignments</h4>
                <p className="text-xs text-slate-300">Conflict warnings: {draftData.conflictsCount}</p>
              </div>
              <button
                onClick={handleApproveDraft}
                className="px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-black text-xs transition shadow-md"
              >
                Approve & Commit to Database
              </button>
            </div>

            {draftData.conflicts?.length > 0 && (
              <div className="space-y-2">
                <h5 className="font-extrabold text-xs uppercase text-amber-800 tracking-wider">Detected Clashes & Warnings</h5>
                <div className="space-y-1.5 max-h-40 overflow-y-auto">
                  {draftData.conflicts.map((c: any, idx: number) => (
                    <div key={idx} className="p-2.5 rounded-lg bg-amber-50 border border-amber-200 text-xs font-bold text-amber-900 flex items-center gap-2">
                      <ShieldAlert className="w-4 h-4 text-amber-600 shrink-0" />
                      {c.message}
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="border border-slate-200 rounded-xl overflow-hidden max-h-64 overflow-y-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-700 font-extrabold">
                  <tr>
                    <th className="p-2.5">Division</th>
                    <th className="p-2.5">Day</th>
                    <th className="p-2.5">Period</th>
                    <th className="p-2.5">Subject</th>
                    <th className="p-2.5">Assigned Teacher</th>
                    <th className="p-2.5">Room</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 font-medium">
                  {draftData.slots?.slice(0, 50).map((s: any, idx: number) => (
                    <tr key={idx} className="hover:bg-slate-50">
                      <td className="p-2.5 font-bold text-slate-800">{s.divisionName}</td>
                      <td className="p-2.5 font-bold text-primary-700">{s.dayOfWeek}</td>
                      <td className="p-2.5 text-slate-700">Period {s.periodNumber}</td>
                      <td className="p-2.5 font-bold text-slate-800">{s.subjectName}</td>
                      <td className="p-2.5 text-slate-700">{s.staffName}</td>
                      <td className="p-2.5 text-slate-600 font-mono">{s.roomNumber}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="flex justify-end gap-3 pt-2 border-t border-slate-100">
              <button onClick={() => setDraftData(null)} className="px-4 py-2 rounded-xl text-xs font-bold text-slate-600 hover:bg-slate-100">
                Discard Draft
              </button>
              <button
                onClick={handleApproveDraft}
                className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-md"
              >
                Approve & Commit to Database
              </button>
            </div>
          </div>
        </Modal>
      )}

    </div>
  );
};

export default TimetablePage;
